name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        docker-compose up
        curl -fsSL https://bun.sh/install | bash

    - name: Install dependencies
      run: |
        # Commands to install necessary dependencies
        # e.g., bun install (or equivalent)

    - name: Run tests
      run: |
        # Command to run tests using 'bun'
        # e.g., bun test (or equivalent)
