name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      uses: oven-sh/setup-bun@v1
      run: |
        docker-compose up -d
        bun help

    - name: Install dependencies
      run: |
        bun install 

    - name: Run tests
      run: |
        bun test
